spring.application.name=onlineQuizPlatform


spring.datasource.url=jdbc:postgresql://localhost:5432/onlineQuizPlatform
spring.datasource.username=postgres
spring.datasource.password=Appa
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8080


